### ISSUE TITLE
Release scoped package?

### ISSUE THREAD

**Issue by Borewit** [webtorrent/airplay-protocol#1]
@feross do you prefer a GitHub dependency, or scoped: [@webtorrent/airplay-protocol](https://www.npmjs.com/package/@webtorrent/airplay-protocol)?

Branch [release](https://github.com/webtorrent/airplay-protocol/tree/release) is prepared for a scoped publication.

Related: https://github.com/webtorrent/airplayer/pull/1#issuecomment-529186869

**Comment by feross** [comment]
I would rather just depend on this with a git dependency since this should hopefully just be temporary. If we publish to npm, then we'll need to do deprecations later.
